create table reservations (
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    reservation_status VARCHAR (30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expired_at TIMESTAMP,

    CONSTRAINT fk_reservation_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_reservation_book FOREIGN KEY (book_id) REFERENCES books (id)
)